return {
	milestone = "M2C-A",
	base = "21ba070d713d4f2275f44222c177de5c3a88b4ac",
	repository_intent = {
		pyright = "interactive LSP",
		ruff = "lint/code-action companion",
		ty = "CLI-only on-demand ty check",
	},
	locked_plugins = {
		LazyVim = "c10948c50b18fae7f256433afdef09e432410480",
		["mason-lspconfig.nvim"] = "40276c4df7e6bdce6801d6c035c6227f9115a855",
		["nvim-lspconfig"] = "16286347bdba1333c7d124d9de9fe6630731b2b2",
	},
	activation = {
		mason_package = "ty",
		lspconfig_server = "ty",
		resolved_cmd = { "ty", "server" },
		resolved_filetypes = { "python" },
		automatic_enable_owner = "mason-lspconfig.nvim",
		native_enable_api = "vim.lsp.enable",
	},
	production = {
		lazy_server_state = { pyright = "enabled", ruff = "enabled", ty = "absent" },
		enabled = { pyright = true, ruff = true, ty = true },
		attached = { "pyright", "ruff", "ty" },
		semantic_producers = { "ty" },
	},
	ty_excluded = {
		lazy_server_state = { pyright = "enabled", ruff = "enabled", ty = "disabled" },
		enabled = { pyright = true, ruff = true, ty = false },
		attached = { "pyright", "ruff" },
		semantic_producers = {},
	},
	capabilities = {
		pyright = {
			semantic_tokens = false,
			completion = true,
			hover = true,
			definition = true,
			references = true,
			rename = true,
			code_action = true,
		},
		ruff = {
			semantic_tokens = false,
			completion = false,
			hover = false,
			definition = false,
			references = false,
			rename = false,
			code_action = true,
		},
		ty = {
			semantic_tokens = true,
			completion = true,
			hover = true,
			definition = true,
			references = true,
			rename = true,
			code_action = true,
		},
	},
	semantic_probe = {
		tag = "python.binding.module_binding",
		token = "module_retry_limit",
		provider = "ty",
		type = "variable",
		modifiers = { "definition" },
		effective_group = "@lsp.type.variable.python",
		effective_role = "DxVariable",
		applied_groups = {
			{ group = "@lsp.mod.definition.python", priority = 126 },
			{ group = "@lsp.type.variable.python", priority = 125 },
			{ group = "@lsp.typemod.variable.definition.python", priority = 127 },
		},
		foregrounds = {
			{ group = "@lsp.type.variable.python", priority = 125, role = "DxVariable" },
		},
	},
	decision = "ADOPT TY AS INTERACTIVE SEMANTIC PROVIDER",
	governance_invariant = "Interactive LSP ownership must be explicit.",
}
