return {
	milestone = "M2C-B",
	base = "5822ddd8982680912484c3aa6dfd661cca59e634",
	decision = "ADOPT TY AS INTERACTIVE SEMANTIC PROVIDER",
	governance_invariant = "Interactive LSP ownership must be explicit.",
	repository_intent = {
		ty = "primary interactive Python LSP",
		ruff = "lint/fix/code-action companion",
		pyright = "installed rollback asset; explicitly disabled",
	},
	locked_plugins = {
		LazyVim = "c10948c50b18fae7f256433afdef09e432410480",
		["mason-lspconfig.nvim"] = "40276c4df7e6bdce6801d6c035c6227f9115a855",
		["nvim-lspconfig"] = "16286347bdba1333c7d124d9de9fe6630731b2b2",
	},
	packages = {
		pyright = { executable = "pyright", lspconfig_server = "pyright" },
		ruff = { executable = "ruff", lspconfig_server = "ruff" },
		ty = { executable = "ty", lspconfig_server = "ty" },
	},
	activation = {
		primary = "ty",
		companion = "ruff",
		rollback = "pyright",
		resolved_ty_cmd = { "ty", "server" },
		resolved_ty_filetypes = { "python" },
		automatic_enable_owner = "mason-lspconfig.nvim",
		native_enable_api = "vim.lsp.enable",
	},
	production = {
		lazy_server_state = { pyright = "disabled", ruff = "enabled", ty = "enabled" },
		automatic_enable_excluded = { pyright = true, ruff = false, ty = false },
		enable_calls = { pyright = 0, ruff = 1, ty = 1 },
		enabled = { pyright = false, ruff = true, ty = true },
		attached = { "ruff", "ty" },
		semantic_producers = { "ty" },
	},
	capabilities = {
		ruff = {
			semantic_tokens = false,
			completion = false,
			hover = false,
			definition = false,
			references = false,
			rename = false,
			code_action = true,
		},
		ty = {
			semantic_tokens = true,
			completion = true,
			hover = true,
			definition = true,
			references = true,
			rename = true,
			code_action = true,
		},
	},
	primary_capability_owners = {
		completion = { "ty" },
		hover = { "ty" },
		definition = { "ty" },
		references = { "ty" },
		rename = { "ty" },
	},
	semantic_probe = {
		tag = "python.binding.module_binding",
		token = "module_retry_limit",
		provider = "ty",
		type = "variable",
		modifiers = { "definition" },
		effective_group = "@lsp.type.variable.python",
		effective_role = "DxVariable",
		applied_groups = {
			{ group = "@lsp.mod.definition.python", priority = 126 },
			{ group = "@lsp.type.variable.python", priority = 125 },
			{ group = "@lsp.typemod.variable.definition.python", priority = 127 },
		},
		foregrounds = {
			{ group = "@lsp.type.variable.python", priority = 125, role = "DxVariable" },
		},
	},
	graph = {
		count = 225,
		sha256 = "a2db03bf6a138c0784d74277adf6f7ee706a5398336305385ced7d3725c0dedf",
		historical_count = 221,
		historical_sha256 = "05ff81df9019ace7bee14a494db1a9e39c7d18426f3b78bae1ef3012a068a276",
	},
}
