-- Generated from icons/contract.toml by icons/generate.py. Do not edit.
return {
  default = {
    directory = { glyph = "", hl = "MiniIconsAzure" },
    file = { glyph = "", hl = "MiniIconsGrey" },
  },
  extension = {
    ["c"] = { glyph = "", hl = "MiniIconsBlue" },
    ["cc"] = { glyph = "", hl = "MiniIconsBlue" },
    ["cmake"] = { glyph = "", hl = "MiniIconsOrange" },
    ["cpp"] = { glyph = "", hl = "MiniIconsBlue" },
    ["css"] = { glyph = "", hl = "MiniIconsBlue" },
    ["csv"] = { glyph = "", hl = "MiniIconsCyan" },
    ["cxx"] = { glyph = "", hl = "MiniIconsBlue" },
    ["env"] = { glyph = "", hl = "MiniIconsCyan" },
    ["fish"] = { glyph = "", hl = "MiniIconsGreen" },
    ["go"] = { glyph = "", hl = "MiniIconsAzure" },
    ["graphql"] = { glyph = "", hl = "MiniIconsPurple" },
    ["h"] = { glyph = "", hl = "MiniIconsBlue" },
    ["hcl"] = { glyph = "", hl = "MiniIconsPurple" },
    ["hh"] = { glyph = "", hl = "MiniIconsBlue" },
    ["hpp"] = { glyph = "", hl = "MiniIconsBlue" },
    ["html"] = { glyph = "", hl = "MiniIconsOrange" },
    ["ini"] = { glyph = "󱁻", hl = "MiniIconsPurple" },
    ["ipynb"] = { glyph = "", hl = "MiniIconsOrange" },
    ["js"] = { glyph = "", hl = "MiniIconsYellow" },
    ["json"] = { glyph = "", hl = "MiniIconsGrey" },
    ["jsonc"] = { glyph = "", hl = "MiniIconsGrey" },
    ["jsx"] = { glyph = "", hl = "MiniIconsYellow" },
    ["kdl"] = { glyph = "", hl = "MiniIconsGrey" },
    ["lock"] = { glyph = "", hl = "MiniIconsYellow" },
    ["lua"] = { glyph = "", hl = "MiniIconsBlue" },
    ["md"] = { glyph = "", hl = "MiniIconsGrey" },
    ["mjs"] = { glyph = "", hl = "MiniIconsYellow" },
    ["nix"] = { glyph = "", hl = "MiniIconsBlue" },
    ["proto"] = { glyph = "", hl = "MiniIconsPurple" },
    ["py"] = { glyph = "", hl = "MiniIconsYellow" },
    ["pyi"] = { glyph = "", hl = "MiniIconsYellow" },
    ["rs"] = { glyph = "", hl = "MiniIconsOrange" },
    ["rst"] = { glyph = "", hl = "MiniIconsGrey" },
    ["scss"] = { glyph = "", hl = "MiniIconsBlue" },
    ["sh"] = { glyph = "", hl = "MiniIconsGreen" },
    ["sql"] = { glyph = "", hl = "MiniIconsCyan" },
    ["tf"] = { glyph = "󱁢", hl = "MiniIconsPurple" },
    ["tfvars"] = { glyph = "󱁢", hl = "MiniIconsPurple" },
    ["toml"] = { glyph = "", hl = "MiniIconsGrey" },
    ["ts"] = { glyph = "", hl = "MiniIconsBlue" },
    ["tsx"] = { glyph = "", hl = "MiniIconsBlue" },
    ["txt"] = { glyph = "", hl = "MiniIconsGrey" },
    ["vim"] = { glyph = "", hl = "MiniIconsGreen" },
    ["xml"] = { glyph = "󰗀", hl = "MiniIconsOrange" },
    ["yaml"] = { glyph = "", hl = "MiniIconsGrey" },
    ["yml"] = { glyph = "", hl = "MiniIconsGrey" },
    ["zig"] = { glyph = "", hl = "MiniIconsYellow" },
    ["zsh"] = { glyph = "", hl = "MiniIconsGreen" },
  },
  file = {
    [".clang-format"] = { glyph = "󱁻", hl = "MiniIconsPurple" },
    [".coveragerc"] = { glyph = "", hl = "MiniIconsGrey" },
    [".dockerignore"] = { glyph = "", hl = "MiniIconsAzure" },
    [".git-blame-ignore-revs"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
    [".gitignore"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
    [".pre-commit-config.yaml"] = { glyph = "󰛢", hl = "MiniIconsGrey" },
    [".shellcheckrc"] = { glyph = "", hl = "MiniIconsGrey" },
    ["CMakeLists.txt"] = { glyph = "", hl = "MiniIconsOrange" },
    ["CMakePresets.json"] = { glyph = "", hl = "MiniIconsOrange" },
    ["CMakeUserPresets.json"] = { glyph = "", hl = "MiniIconsOrange" },
    ["CODE_OF_CONDUCT.md"] = { glyph = "", hl = "MiniIconsGrey" },
    ["CONTRIBUTING.md"] = { glyph = "", hl = "MiniIconsGrey" },
    ["Cargo.lock"] = { glyph = "", hl = "MiniIconsOrange" },
    ["Cargo.toml"] = { glyph = "", hl = "MiniIconsOrange" },
    ["DCO"] = { glyph = "󰡯", hl = "MiniIconsGrey" },
    ["Dockerfile"] = { glyph = "", hl = "MiniIconsAzure" },
    ["Justfile"] = { glyph = "", hl = "MiniIconsOrange" },
    ["LICENSE"] = { glyph = "", hl = "MiniIconsYellow" },
    ["MANIFEST.in"] = { glyph = "", hl = "MiniIconsYellow" },
    ["Makefile"] = { glyph = "", hl = "MiniIconsOrange" },
    ["README.md"] = { glyph = "󰂺", hl = "MiniIconsYellow" },
    ["SECURITY.md"] = { glyph = "󰒃", hl = "MiniIconsRed" },
    ["Taskfile.yml"] = { glyph = "", hl = "MiniIconsOrange" },
    ["build.zig"] = { glyph = "", hl = "MiniIconsYellow" },
    ["build.zig.zon"] = { glyph = "", hl = "MiniIconsYellow" },
    ["bun.lock"] = { glyph = "", hl = "MiniIconsYellow" },
    ["compose.yaml"] = { glyph = "", hl = "MiniIconsAzure" },
    ["docker-compose.yml"] = { glyph = "", hl = "MiniIconsAzure" },
    ["go.mod"] = { glyph = "", hl = "MiniIconsAzure" },
    ["go.sum"] = { glyph = "", hl = "MiniIconsAzure" },
    ["meson.build"] = { glyph = "", hl = "MiniIconsOrange" },
    ["package-lock.json"] = { glyph = "", hl = "MiniIconsYellow" },
    ["package.json"] = { glyph = "", hl = "MiniIconsYellow" },
    ["pnpm-lock.yaml"] = { glyph = "", hl = "MiniIconsYellow" },
    ["pyproject.toml"] = { glyph = "", hl = "MiniIconsYellow" },
    ["requirements.txt"] = { glyph = "", hl = "MiniIconsYellow" },
    ["rust-toolchain.toml"] = { glyph = "", hl = "MiniIconsOrange" },
    ["uv.lock"] = { glyph = "", hl = "MiniIconsYellow" },
    ["yarn.lock"] = { glyph = "", hl = "MiniIconsYellow" },
  },
}
